name: convert videos

on:
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Depends
        run: |
          sudo /bin/bash ./install_indexer.sh
      - name: Download rclone config
        run: |
          sudo python3 ./RcloneConfig.py download \
          ${{ secrets.firebase_api_key }} ${{ secrets.firebase_password }}
      - name: rclone mount
        run: | 
          sudo mkdir /iconvert && \
          sudo rclone mount od_lizkes_backup_root:/ /iconvert \
          --buffer-size 128M --allow-other \
          --timeout 20s --contimeout 10s \
          --low-level-retries 10 --retries 3 \
          --vfs-cache-mode full --vfs-read-ahead  512M \
          --log-level INFO --drive-acknowledge-abuse \
          --daemon 2>&1
      - name: Run indexer
        run: |
          sudo python3 -m app.run --role indexer \
          --input-dir /iconvert/视频 \
          --firebase-api-key ${{ secrets.firebase_api_key }} \
          --firebase-db-url https://lizkes-default-rtdb.asia-southeast1.firebasedatabase.app/ \
          --firebase-project-id lizkes \
          --firebase-email lizkes@lizkes.com \
          --firebase-password ${{ secrets.firebase_password }}
  convert:
    runs-on: ubuntu-22.04
    needs: index
    strategy:
      matrix:
        sleep_time: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300]
      fail-fast: false
    steps:
      - name: Sleep
        run: sleep ${{ matrix.sleep_time }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Depends
        run: |
          sudo /bin/bash ./install_converter.sh
      - name: Download rclone config
        run: |
          sudo python3 ./RcloneConfig.py download \
          ${{ secrets.firebase_api_key }} ${{ secrets.firebase_password }}
      - name: rclone mount
        run: | 
          sudo mkdir /iconvert && \
          sudo rclone mount od_lizkes_backup_root:/ /iconvert \
          --buffer-size 128M --allow-other \
          --timeout 20s --contimeout 10s \
          --low-level-retries 10 --retries 3 \
          --vfs-cache-mode full --vfs-read-ahead  512M \
          --log-level INFO --drive-acknowledge-abuse \
          --daemon 2>&1
      - name: Run converter
        run: |
          sudo python3 -m app.run --role converter \
          --input-dir /iconvert/视频 \
          --output-dir /iconvert/视频 \
          --remote-output-dir od_lizkes_backup_root:/视频 \
          --format webm --keep-origin \
          --firebase-api-key ${{ secrets.firebase_api_key }} \
          --firebase-db-url https://lizkes-default-rtdb.asia-southeast1.firebasedatabase.app/ \
          --firebase-project-id lizkes \
          --firebase-email lizkes@lizkes.com \
          --firebase-password ${{ secrets.firebase_password }} \
          --owner-repo ${{ github.repository }} \
          --workflow-id convert \
          --github-token ${{ secrets.gh_token }}
